version: "2.4"

services:
  db:
    image: mariadb:10.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    env_file:
      - ./.env
  app:
    image: matomo
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8888
    env_file:
      - ./.env